### ISSUE TITLE
Cannot find module 'jsreport'

### ISSUE THREAD

**Issue by jeroenvheel** [jsreport/jsreport-azure-functions-starter-kit#2]
Hi i have a issue when trying to run the Azure function

The error i get is 'Cannot find module 'jsreport''

How can i solve this issue?

> 2021-11-09T12:57:10.378 [Error] Executed 'Functions.JsReports' (Failed, Id=19b33b0a-c6cc-48c0-bed8-423d5d7a200c, Duration=17ms)Result: FailureException: Worker was unable to load function JsReports: 'Error: Cannot find module 'jsreport'Require stack:- C:\home\site\wwwroot\JsReports\index.js- C:\Program Files (x86)\SiteExtensions\Functions\3.3.1\workers\node\worker-bundle.js- C:\Program Files (x86)\SiteExtensions\Functions\3.3.1\workers\node\dist\src\nodejsWorker.js'Stack: Error: Cannot find module 'jsreport'Require stack:- C:\home\site\wwwroot\JsReports\index.js- C:\Program Files (x86)\SiteExtensions\Functions\3.3.1\workers\node\worker-bundle.js- C:\Program Files (x86)\SiteExtensions\Functions\3.3.1\workers\node\dist\src\nodejsWorker.jsat Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)at Function.Module._load (internal/modules/cjs/loader.js:667:27)at Module.require (internal/modules/cjs/loader.js:887:19)at require (internal/modules/cjs/helpers.js:74:18)at Object.<anonymous> (C:\home\site\wwwroot\JsReports\index.js:1:18)at Module._compile (internal/modules/cjs/loader.js:999:30)at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)at Module.load (internal/modules/cjs/loader.js:863:32)at Function.Module._load (internal/modules/cjs/loader.js:708:14)at Module.require (internal/modules/cjs/loader.js:887:19)

**Comment by pofider** [comment]
I see some kind of windows based stacktrace. JsReport doesn't run on windows based app service/function.
Please check the following tutorial 
https://jsreport.net/learn/azure-functions-serverless

Note you need to use jsreport v2 now, because azure functions don't support node 16, which is required by jsreport v3, yet.

**Comment by jeroenvheel** [comment]
Thanks! Wil change the stack and try it.

**Comment by jeroenvheel** [comment]
The change to Linux worked
