### ISSUE TITLE
Node 16 reaching EOL at the Azure Platform

### ISSUE THREAD

**Issue by Rudde** [jsreport/jsreport-azure-functions-starter-kit#6]
Node 16, which this project depends on will reach end of life September 11th 2023. When will we see it on a newer LTS of node?

**Comment by pofider** [comment]
jsreport runs just fine with node 18.
What problems are you experiencing?

**Comment by Rudde** [comment]
Oh, I followed the guide, and I still see it lists Node 16 as a prerequisites (https://jsreport.net/learn/azure-functions-serverless)

**Comment by Rudde** [comment]
While I get to to work locally on Node 18, I cannot deploy it to as an Azure function.

I get the following error

`10:28:20 AM dokflyt-jsreport: Starting deployment...
10:28:20 AM dokflyt-jsreport: Creating zip package...
10:28:21 AM dokflyt-jsreport: Zip package size: 2.74 MB
10:28:21 AM dokflyt-jsreport: Fetching changes.
10:28:22 AM dokflyt-jsreport: Cleaning up temp folders from previous zip deployments and extracting pushed zip file /tmp/zipdeploy/33bc1dcc-6c04-4649-a261-ca305b1cde89.zip (2.62 MB) to /tmp/zipdeploy/extracted
10:28:25 AM dokflyt-jsreport: Updating submodules.
10:28:26 AM dokflyt-jsreport: Preparing deployment for commit id 'b5a5ad7d-a'.
10:28:27 AM dokflyt-jsreport: PreDeployment: context.CleanOutputPath False
10:28:27 AM dokflyt-jsreport: PreDeployment: context.OutputPath /home/site/wwwroot
10:28:27 AM dokflyt-jsreport: Repository path is /tmp/zipdeploy/extracted
10:28:27 AM dokflyt-jsreport: Running oryx build...
10:28:27 AM dokflyt-jsreport: Command: oryx build /tmp/zipdeploy/extracted -o /tmp/build/expressbuild --platform nodejs --platform-version 18 -i /tmp/8db9fc5186872cf
10:28:28 AM dokflyt-jsreport: Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
10:28:28 AM dokflyt-jsreport: You can report issues at https://github.com/Microsoft/Oryx/issues
10:28:28 AM dokflyt-jsreport: Oryx Version: 0.2.20230508.1, Commit: 7fe2bf39b357dd68572b438a85ca50b5ecfb4592, ReleaseTagName: 20230508.1
10:28:28 AM dokflyt-jsreport: Build Operation ID: 8a51e588d056f92d
10:28:28 AM dokflyt-jsreport: Repository Commit : b5a5ad7d-a262-4bda-9895-9a3276e346db
10:28:28 AM dokflyt-jsreport: OS Type           : bullseye
10:28:28 AM dokflyt-jsreport: Image Type        : githubactions
10:28:29 AM dokflyt-jsreport: Detecting platforms...
10:28:30 AM dokflyt-jsreport: Detected following platforms:
10:28:30 AM dokflyt-jsreport:   nodejs: 18.16.1
10:28:31 AM dokflyt-jsreport: Using intermediate directory '/tmp/8db9fc5186872cf'.
10:28:31 AM dokflyt-jsreport: Copying files to the intermediate directory...
10:28:31 AM dokflyt-jsreport: Done in 1 sec(s).
10:28:31 AM dokflyt-jsreport: Source directory     : /tmp/8db9fc5186872cf
10:28:31 AM dokflyt-jsreport: Destination directory: /tmp/build/expressbuild
10:28:31 AM dokflyt-jsreport: Removing existing manifest file
10:28:31 AM dokflyt-jsreport: Creating directory for command manifest file if it does not exist
10:28:31 AM dokflyt-jsreport: Creating a manifest file...
10:28:31 AM dokflyt-jsreport: Node Build Command Manifest file created.
10:28:31 AM dokflyt-jsreport: Using Node version:
10:28:31 AM dokflyt-jsreport: v18.16.1
10:28:31 AM dokflyt-jsreport: Using Npm version:
10:28:32 AM dokflyt-jsreport: 9.5.1
10:28:32 AM dokflyt-jsreport: Running 'npm install'...
10:28:40 AM dokflyt-jsreport: npm ERR! code ENOTSUP
10:28:41 AM dokflyt-jsreport: npm ERR! syscall link
10:28:41 AM dokflyt-jsreport: npm ERR! path /home/.npm/_cacache/tmp/e1748c9b
10:28:41 AM dokflyt-jsreport: npm ERR! dest /home/.npm/_cacache/content-v2/sha512/ec/0b/755947adb637124475c2c98b53b1e95b95c1e5f4f2451552a2080cbf6d8f7bf813d95d2436c1bab43fdb3cb4ad86edd1507cd9e52673c0880ad505506c7c
10:28:41 AM dokflyt-jsreport: npm ERR! errno -95
10:28:41 AM dokflyt-jsreport: npm ERR! ENOTSUP: operation not supported on socket, link '/home/.npm/_cacache/tmp/e1748c9b' -> '/home/.npm/_cacache/content-v2/sha512/ec/0b/755947adb637124475c2c98b53b1e95b95c1e5f4f2451552a2080cbf6d8f7bf813d95d2436c1bab43fdb3cb4ad86edd1507cd9e52673c0880ad505506c7c'
10:28:41 AM dokflyt-jsreport: npm ERR! A complete log of this run can be found in:
10:28:41 AM dokflyt-jsreport: npm ERR!     /home/.npm/_logs/2023-08-18T08_28_32_482Z-debug-0.log
10:28:44 AM dokflyt-jsreport: /opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /tmp/build/expressbuild --platform nodejs --platform-version 18 -i /tmp/8db9fc5186872cf
10:28:44 AM dokflyt-jsreport: Generating summary of Oryx build
10:28:44 AM dokflyt-jsreport: Deployment Log file does not exist in /tmp/oryx-build.log
10:28:45 AM dokflyt-jsreport: The logfile at /tmp/oryx-build.log is empty. Unable to fetch the summary of build
10:28:45 AM dokflyt-jsreport: Deployment Failed. deployer = ms-azuretools-vscode deploymentPath = Functions App ZipDeploy. Extract zip. Remote build.
10:28:56 AM dokflyt-jsreport: Deployment failed.`

**Comment by pofider** [comment]
This isn't related to jsreport, but the `npm i` somehow doesn't work there.
Try to clan npm cache.
Or google that issue `ENOTSUP: operation not supported on socket, link`
